[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
fm_core = { path = "../../fm_core", default-features = false }
iced.workspace = true
time.workspace = true
anyhow.workspace = true
async-std.workspace = true
rfd.workspace = true
